### ISSUE TITLE
Connect Newslink to pull data from the heroku API

### ISSUE THREAD

**Issue by bryanbraun** [bryanbraun/petitions-newslink#2]
Right now, it processes all the issues and timestamps manually by looping through javascript objects and arrays. Connecting to the API will speed up this process significantly.

**Comment by bryanbraun** [comment]
The data is available at http://wethedata.herokuapp.com/issues

I'll start setting up the calls to this data. In the mean time, I think we may need to rename one of the properties from "petition_time_series" to "data" (which is the property name highcharts will be expecting: http://api.highcharts.com/highstock#series). We'll see if any more renaming is needed as we hook it up.

**Comment by typesend** [comment]
_petition_time_series_ has been renamed to _data_.  The change has been deployed as well.

**Comment by bryanbraun** [comment]
Thanks. I've pushed this fix up into the repo, so the loadtimes are a lot better now. However, it looks like we need to sort the data output by the api to be ascending by timestamp (highcharts doesn't like the unsorted data we're giving it: http://www.highcharts.com/errors/15).

Here's an example of the sorted data format highcharts is expecting: http://www.highcharts.com/samples/data/jsonp.php?filename=aapl-c.json&callback

@typesend I'm assigning this ticket to you, so you can sort the data, and check it against what's being output into the chart.

**Comment by typesend** [comment]
@bryanbraun I just deployed the fix and verified that it is sorting by timestamp in ascending order.

http://wethedata.herokuapp.com/issues

**Comment by bryanbraun** [comment]
Thanks, that looks a lot better.

I noticed that the result-set being plotted looks a different from the one at http://wethedata.herokuapp.com... any thoughts on why that may be?

Actually, looking closer, the time scale appears to be off, so I can start by looking at how highcharts is handling the timestamps. Spinning that off into a separate ticket: https://github.com/bryanbraun/petitions-newslink/issues/9
