### ISSUE TITLE
Move the code for the "We the data" backend into github

### ISSUE THREAD

**Issue by bryanbraun** [bryanbraun/petitions-newslink#3]

**Comment by typesend** [comment]
@bryanbraun @lkhaas Please let me know when you've pushed your changes to the repo. Then I can merge your most recent work with the rails codebase and smoosh it all together and kill my old wethedata repo.

**Comment by bryanbraun** [comment]
Cool. I'll continue to push my changes up to github.

**Comment by bryanbraun** [comment]
I'm not sure this ticket is needed anymore, now that the Heroku app files have been pushed to github.

I did notice that there was an option in Heroku to link your app to a github repository. @typesend, do you think we should do that? I don't know what that kind of connection is for.

**Comment by bryanbraun** [comment]
Closing, since these files are now in our github repo.
