### ISSUE TITLE
Host the full code on Heroku so we can have a working demo.

### ISSUE THREAD

**Issue by bryanbraun** [bryanbraun/petitions-newslink#4]
This should probably be done after the next round of fixes and optimizations are set up, so everything is working properly. It depends on: https://github.com/bryanbraun/petitions-newslink/issues/1, https://github.com/bryanbraun/petitions-newslink/issues/2 and possibly some others.

Also, once this is up, we should link to it in the readme and add the link here: https://github.com/WhiteHouse/ndoch-hackathon/issues/13

**Comment by typesend** [comment]
I'm manually migrating over the static html, css, and js into my typesend/we rails app. So going to plain ol' http://wethedata.herokuapp.com/ will soon bring up Bryan's frontend. @bryanbraun @lkhaas

**Comment by typesend** [comment]
The working demo is now live at http://wethedata.herokuapp.com/ and I'm holding off with the hostname change until you guys check in your code changes, per #6

**Comment by eshtadc** [comment]
Hey Ben - how can I get the back-end you made to return jsonp instead of raw json?

**Comment by typesend** [comment]
I
​ just deployed support for jsonp. Just use the common ?callback=whatever
style based on the existing /issues and /petitions/0/1/9 paths. :)

Note: I added this in such a way that all future api calls we might add in
will automatically have support for JSONP calls.

Rock on.

**Comment by eshtadc** [comment]
Perfect.  Did exactly what I needed and I've been able to get the barebones functionality migrated into JS and uploaded into the repo.

**Comment by bryanbraun** [comment]
I still need to finish up https://github.com/bryanbraun/petitions-newslink/issues/1, and we'll need to work the bugs out of https://github.com/bryanbraun/petitions-newslink/issues/2 and then we should be able to push a fresh and fully functional version up to our Heroku app.

By the way, our project is now featured at https://petitions.whitehouse.gov/how-why/api-gallery. Once we close these last few issues, I'll look into getting a demo link up there.

**Comment by typesend** [comment]
I know #1 is still technically open due to the occasional NYT API error, but is now  a good time for me to semi-destructively merge the repos together as planned? Or should I continue to hold off until #1 is officially closed for good?

**Comment by typesend** [comment]
Okay, merging the two repos was easier than I expected it would be. My complete commit history from typesend/we is now merged into this repository.

The static html and js files still need to be moved to their correct places inside the conventional rails application directory structure...I'm doing this next.

**Comment by typesend** [comment]
@bryanbraun @lkhaas Take note of the rather more complex directory structure. To track down your js, css, and html poke around in the /app/assets and /views/layouts and /views/welcome directories.  You'll want to do a fresh pull from this repo to update your local copies.

**Comment by typesend** [comment]
Okay, well the demo is online and semi-working. Gotta load more data in there and correct whatever issues are remaining with the news api, but I'm closing this ticket nonetheless.
