### ISSUE TITLE
The chart's timescale is off.

### ISSUE THREAD

**Issue by bryanbraun** [bryanbraun/petitions-newslink#9]
The timescale is off and that appears to be throwing off the data curve. I'll assign this to myself to look into how highcharts is interpreting the timestamps.

**Comment by bryanbraun** [comment]
Looked into this, and it looks like we need the timestamps to be in the Unix "milliseconds format." See more here:
http://stackoverflow.com/questions/10160822/handling-unix-timestamp-with-highcharts#answer-10161080

My bad for not catching that earlier, but the fix should be pretty easy... just multiply each timestamp by 1000. It makes most sense to take care of this in the heroku api, so I'm assigning to @typesend. Ben, let me know if there's any way I can help.

**Comment by typesend** [comment]
@bryanbraun Fixed.
